name: Android Build

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Update Version and Commit Changes
        run: |
          version_code=$(grep "versionCode" android/app/build.gradle | sed -E 's/.*([0-9]+).*/\1/')
          version_name=$(grep "versionName" android/app/build.gradle | sed -E 's/.*"([0-9]+).*/\1/')

           # Increment version code if version name is 10
           if [ "$version_name" = "10" ]; then
               version_code=$((version_code + 1))
               version_name="0"
           else
               # Increment version name
               version_name=$((version_name + 1))
           fi

           # Update version code and name in build.gradle
           sed -i "s/versionCode [0-9]*/versionCode $version_code/" android/app/build.gradle
           sed -i "s/versionName \"$version_name\"/versionName \"$version_name\"/" android/app/build.gradle
           echo "Updated version code: $version_code, version name: $version_name"
           # Commit changes
           git config --global user.email "github-actions@github.com"
           git config --global user.name "GitHub Actions"
           git add android/app/build.gradle
           git commit -m "Increment version code and name"
           git push

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - name: Build Android app
        run: |
          yarn build
          yarn run build-android

      - name: Build APK
        run: |
          cd android && ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/*.apk
      - name: Build apk bundle
        run: |
          cd android &&./gradlew bundleDebug
      - name: Upload apk bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: ./android/app/build/outputs/bundle/debug/*.aab
