name: Android Build

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - name: Build Android app
        run: |
          yarn build
          yarn run build-android
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ vars.KEYSTORE_BASE_64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}

        run: |
          echo "base64------>: $ENCODED_STRING"
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      - name: Build Release APK
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}
          REACT_APP_REDIRECT_URL: ${{ vars.REACT_APP_REDIRECT_URL }}
        run: |
          cd android && ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./android/app/release/*.apk
      - name: Build Release apk bundle
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}
          REACT_APP_REDIRECT_URL: ${{ vars.REACT_APP_REDIRECT_URL }}
        run: |
          cd android &&./gradlew bundleRelease --stacktrace
      - name: Upload apk bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./android/app/release/*.aab
