name: Android Build

on:
  push:
    branches:
      - main
env:
  RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
  RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}
  REACT_APP_REDIRECT_URL: ${{ vars.REACT_APP_REDIRECT_URL }}
jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Read JSON file
        run: |
          ls
          content=`cat ./public/meta.json`
          echo "Current version is \`$content\`"
      - name: Extract existing version code
        run: |
          # Getting version code from meta.json file
          current_version=content=`cat ./public/meta.json`

          # Get existing version code from build.gradle
          # version_code=$(grep "versionCode" android/app/build.gradle | awk '{print $2}' | tr -d '\n')

          # Increment existing version code by 1
          # version_code=$((version_code + 1))

          # Increment version number
          major_version=$(echo "$current_version" | awk -F '.' '{print $1}')
          minor_version=$(echo "$current_version" | awk -F '.' '{print $2}')
          echo "Major Version : $major_version"
          echo "Minor Version : $minor_version"
          if [ "$minor_version" -eq "10" ]; then
              new_version="$((major_version + 1)).0"
          else
              next_version=$((minor_version + 1))
              new_version="$major_version.$next_version"
          fi

          # Update build.gradle with new version code and name
          echo "$version_code - $version_name"
          sed -i "s/versionCode [0-9]\+/versionCode $major_version/g" android/app/build.gradle
          # Update version name in the project (adjust this command as per your project structure)
          sed -i "s/versionName \"$current_version\"/versionName \"$current_version\"/" android/app/build.gradle

          echo "version name=$current_version and version code=$major_version"

      - name: Commit and push changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          git commit -am "Bump version code and change version name"
          git push origin ${{ github.ref_name }}

      - run: yarn install

      - name: Build Android app
        run: |
          yarn build
          yarn run build-android
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ vars.KEYSTORE_BASE_64 }}
          # RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
          # RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
          # RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      - name: Build Release APK
        # env:
        #   RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
        #   RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
        #   RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}
        #   REACT_APP_REDIRECT_URL: ${{ vars.REACT_APP_REDIRECT_URL }}
        run: |
          cd android && ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/release/*.apk
      - name: Build Release apk bundle
        # env:
        #   RELEASE_KEYSTORE_PASSWORD: ${{ vars.RELEASE_KEYSTORE_PASSWORD }}
        #   RELEASE_KEYSTORE_ALIAS: ${{ vars.RELEASE_KEYSTORE_ALIAS }}
        #   RELEASE_KEY_PASSWORD: ${{ vars.RELEASE_KEY_PASSWORD }}
        #   REACT_APP_REDIRECT_URL: ${{ vars.REACT_APP_REDIRECT_URL }}
        run: |
          cd android &&./gradlew bundleRelease --stacktrace
      - name: Upload apk bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle-release
          path: ./android/app/build/outputs/bundle/release/*.aab
  new-tests:
    needs: build
    uses: ./.github/workflows/build.yml
