name: Android Build

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Update Apk Version
        run: |
          version_code=$(($(grep "versionCode" android/app/build.gradle | sed -E 's/.*([0-9]+).*/\1/') + 1))
          sed -i "s/versionCode [0-9]*/versionCode $version_code/" android/app/build.gradle

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - name: Build Android app
        run: |
          yarn build
          yarn run build-android

      - name: Build APK
        run: |
          cd android && ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/*.apk
      - name: Build apk bundle
        run: |
          cd android &&./gradlew bundleDebug
      - name: Upload apk bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: ./android/app/build/outputs/bundle/debug/*.aab
