name: Android Build

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - name: Build Android app
        run: |
          yarn build
          yarn run build-android

      - name: Build APK
        run: |
          cd android && ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ./android/app/build/outputs/apk/debug/*.apk
